services:
  - type: web
    name: travelxplore-server
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
